site_name: MMCU Documentation
site_description: Modular MCU framework using C++20 modules
site_dir: site
docs_dir: docs

theme:
  name: mkdocs

nav:
  - Home: index.md
  - Setup: setup.md
  - User Guide: guide.md
  - Tools: tools.md
  - Platform Tools: platform-tools.md
  - Build And Run: build.md
  - Configure: configure.md
  - Run: run.md
  - Flash: flash.md
  - Clean: clean.md
  - Platform: platform.md
  - Target Modules: target-modules.md
  - Modular Target: target.md
  - Modular Board: board.md
  - YAML Schemas: yaml.md
  - Modular Peripherals: peripherals.md
  - ARM Targets:
      - Cortex-M0/M0+ Integration: targets-arm/cortex-m0-m0plus.md
      - RP2040/RP2350 Integration: targets-arm/rp2040-rp2350.md
  - Platform Modules: platform-modules.md
  - Native Platforms:
      - Linux: platforms-native/linux.md
  - Bare-Metal Platforms:
      - MCU: platforms-baremetal/mcu.md
      - CMSIS: platforms-baremetal/cmsis.md
      - pico-sdk: platforms-baremetal/pico-sdk.md
  - Project Layout: layout.md
  - Libraries: libraries.md
  - Drivers: drivers.md
  - Module Definition: module.md
  - Modules: modules.md
  - Arm Modules: modules/arm.md
  - Application: application.md
  - Dependencies: dependencies.md
  - Dependency DSL: dependency-dsl.md
  - Mapping: mapping.md
  - Resolving: resolving.md
  - Build Process: process.md
  - External Dependencies: external-dependencies.md
  - Book:
      - Overview: book/index.md
      - Chapter 1: book/chapter_1.md
      - Chapter 2: book/chapter_2.md
      - Chapter 3: book/chapter_3.md
      - Chapter 4: book/chapter_4.md
      - Chapter 5: book/chapter_5.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
